# GitHub Pages configuration for C++ Data Structure Visualizer Documentation

# Theme
theme: minima
title: "C++ Data Structure Visualizer"
description: "Analyze and visualize nested linked-list data structures for parallel processing optimization"

# Site settings
baseurl: ""
url: "https://yourusername.github.io"
repository: "yourusername/cpp-data-visualizer"

# Author information
author:
  name: "Your Name"
  email: "your.email@example.com"

# Social links
github_username: yourusername

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Navigation
navigation:
  - title: "Home"
    url: /
  - title: "Getting Started"
    url: /getting-started/
  - title: "User Guide"
    url: /user-guide/
  - title: "API Reference"
    url: /api-reference/
  - title: "Architecture"
    url: /architecture/
  - title: "Development"
    url: /development/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include files
include:
  - _pages